### PR TITLE
Makes dd use ArgParser

### PR DESCRIPTION
**Pull request by tmccrmck**
`dd` now adheres to ArgParser. All core utilities should now use ArgParser.

More work needs to be done to address #126.

### CODE REVIEW

**Comment by simondesloges** [comment]
Doesn't it feels a bit weird to add a method in the ArgParser dedicated to `dd`? 
Maybe a more general solution could be implemented, one that would allow any command to have opts without the `--` before, like `dd` has.
The `Value` enum could be extended to have a third value (ex: `OptWithoutDashes`, I can't find a better name). Another way could be to add a boolean value, indicating whether or not the opt should be used with dashes, to the `Value::Opt` variant.

**Comment by tmccrmck** [comment]
I agree -- it feels wrong to add a method dedicated only to `dd`. We could allow `opts` without the `--` but I don't think it would be used by anything else.

Another option is to make `dd` follow how all other utils use opts. The reason `dd` has it's weird syntax is a historical quirk and we shouldn't feel bound by it. I don't think this looks bad per se:

`dd --if=/foo/bar --of=/dev/null --bs=1M`

**Comment by DaanHoogland** [comment]
i agree that a method parse_dd iss not desireable. on the other hand, this old quirk is not uncommon. we have flags and opts now, we could call this a setting and have a generic method for that.

side note; some command have 'command' arguments (modern varyity is git) as opposed to their arguments as well.

**Comment by tmccrmck** [comment]
OK. @simondesloges @DaanHoogland why don't you guys take a look. I've implemented a Setting argument.

@jackpot51 This PR should be ready to go.

**Comment by jackpot51** [comment]
Looks good to me, thanks for the work!

**Comment by DaanHoogland** [comment]
sorry for joining in late, great work

**Pull request merged**
