### PR TITLE
Add support for stdin and stdout for dd

### LINKED ISSUE #126: dd should read from stdin and write to stdout
If `dd` is not supplied with `if=` the standard input should be used.

And if it is not supplied with `of=` then standard output should be used.

### PR DESCRIPTION
**Pull request by Mojo4242**
- if no input file is given, read from stdin
- if no output file is given, write to stdout

closes #126

### CODE REVIEW

**Comment by tmccrmck** [comment]
Great way of doing it! Looks good 👍

**Comment by tmccrmck** [comment]
Actually reading from stdin does not work. It says that one byte is copied but it doesn't copy any bytes.

**Comment by simondesloges** [comment]
I tried reading from stdin and outputing both to stdout and to a file and the bytes are copied alright. Tested on Linux, not Redox though.

@tmccrmck, care to elaborate on what is not working?

I only noticed one potential tiny problem:
This implementation of reading from stdin will stop reading when Enter is pressed, as
opposed to waiting until EOF (ctrl+d) before stopping to read.

**Comment by Mojo4242** [comment]
I confirm, I got the same issue: ok under Linux and only read one character on Redox

**Comment by tmccrmck** [comment]
Yep. In Redox, first character entered and it stops reading from stdin.

**Comment by simondesloges** [comment]
Make that three: I tested on Redox and indeed, as soon as I hit a key, it stops and copies nothing... Outputing to stdout or file works and reading from file works. I tried writing to stdout with the `cat` command as well (still on Redox) and it didn't seem to register any input when reading from stdin. Could this be an ion issue?

**Comment by Mojo4242** [comment]
```
ion:file:/root# echo 12345 | dd of=out
0+1 records in
0+1 records out
6 bytes (6B) copied, 0.009001144 s, 666B/s

ion:file:/root# cat out
12345
```

Stdin reading seems fine, maybe a bug with Ion ?

**Comment by tmccrmck** [comment]
I think it's a bug with Ion. [I would start looking here first.](https://github.com/redox-os/ion/blob/master/src/variables.rs#L195-L202)

**Comment by simondesloges** [comment]
When I run the commands (`dd` and `cat`) through Ion on Linux instead of Redox, they work as intended. So, this might also be a Redox issue?

**Comment by simondesloges** [comment]
**About the "as soon as I hit a key, it stops and copies nothing" thing.**
The way the reading code of `dd` is written, when the amount of bytes read from the input source is less then the `bs` setting, it copies whatever it was able to read, copies it to the output and then stops waiting for input and ends.

The default for `bs` is 512 and when reading bytes from `stdin` it looks like it's only reading one char at a time.

Running `dd` with `bs=1` results in `dd` continuously reading from stdin instead of giving up after one read. It seems like the output is flushed only when the whole copying is done, but when reading with `bs=1` from stdin, the copying is never done, as we don't have a way to indicate EOF (on Redox, as far as I know).

So I tried the following in an Ion terminal:
```
    dd bs=1 of=test.txt
```
then typed a bunch of text, got no feedback from stdout, and closed the terminal window, thus also killing `dd`. Then I looked into the `test.txt` file and inside was the text I typed.

**My conclusion**
So... reading from stdin is actually working, and if you test it, writing to stdout should also work, as long as you allow it to finish reading (ex: set `if=` to a file).

I don't know much about the implementation of shells, but it looks like bash, for exemple, doesn't directly offer access to stdin and instead buffers the input text and allows modifying it and, when Enter is pressed, the buffer is sent (I think that's libreadline? again, I don't know much on this). Then, because the buffer contains a `\n` from the Enter keypress, the output is flushed and thus shown?

I thought to myself: " So, what I think now is that this is an Ion issue, in that it doesn't offer this sort of input buffering I just talked about. "

But then, the fact that Ion + [`dd` and `cat`] actually work well on Linux kinda destroys this argument... I am out of ideas for now.

Also, while trying to understand what is wrong here, I discovered that, in Redox, a press to Enter seems to read the value 13, that is `\r` instead of 10 (`\n`). I am a bit confused by that.

**Comment by jackpot51** [comment]
@simondesloges In that case, it can be fixed in `vesad` where stdio is served. I will merge, preferring to create an issue here: https://github.com/redox-os/drivers

**Pull request merged**
