### PR TITLE
Refactored cat.rs to use the coreutils::ArgParser.

### PR DESCRIPTION
**Pull request by glaxx**
Hello,

I've managed to rewrite necessary parts of cat.rs to use ArgParser.

Comments welcome :)

Greetings,

glaxx

### CODE REVIEW

**Comment by jackpot51** [comment]
Very cool! I hope @stratact will take a look

**Comment by stratact** [comment]
@jackpot51 sure thing.

@glaxx I appreciate you doing the work. :smile: 

I got one critique and that is you don't need all the `bool` and `path` fields in `Program` anymore. Those can be removed since each flag you add to the ArgParser holds a bool already and detects whenever the flag has been used or not when `ArgParser::initialized()` is called, and `ArgParser.args` already holds the paths. So all of that work is already taken care of for you, so there is a bit of redundancy you can remove if you don't mind do so. ;)

**Comment by glaxx** [comment]
@stratact You're absolutely right. I'll change it :). Thanks for the help btw.!

**Comment by stratact** [comment]
@glaxx just so you know, @ticki was cleaning through our inactive accounts in Mattermost by removing them and I noticed he accidentally removed yours. So if you could, please ask to be re-invited back, it was our mistake.

**Comment by stratact** [comment]
@glaxx, how is cat.rs turning out?

**Comment by DaanHoogland** [comment]
@stratact I reviewded this and found a little problem with your comment; the parser is out of scope when the flags are used. The code is out of date however so I have created a rebased version of this PR.

**Comment by jackpot51** [comment]
Closed in favor of #112

**Pull request closed without merging**
