### PR TITLE
Rustify

### PR DESCRIPTION
**Pull request by mmstick**
Submitting a handful of improvements to the source code that I wrote a while back
to fit better with Rust's functional style.

### CODE REVIEW

**Comment by rushsteve1** [comment]
Some good improvements but IMO it loses readability. Maybe add some comments just to spruce things up.
(FYI I have no real say in whether this is accepted or not, just my opinions.)

**Comment by ticki** [comment]
Nice stuff. I agreewith @rushsteve1. Perhaps clean it up a little?

**Comment by mmstick** [comment]
I've added code comments and additional improvements.

**Comment by mmstick** [comment]
Just pushed a change to `cat` to eliminate the redundancy of having two functions that do the same thing by using input generics so that whether the input is stdin or a file, it matters not.

**Comment by rushsteve1** [comment]
This seems very well done to me. It's up to @ticki if it gets accepted.

**Comment by jackpot51** [comment]
Looks very good!

**Comment by ticki** [comment]
Sorry for the delay.

**Pull request merged**
