### PR TITLE
Add Test Command

### PR DESCRIPTION
**Pull request by mmstick**
This will add the test command to our list of provided utilities, which is almost feature complete. It's simply missing a few flag parameters that I wasn't sure how to implement right now and the ability to evaluate multiple expressions via parentheses. The `MAN_PAGE` variable only contains the features that I have implemented.

### CODE REVIEW

**Comment by Ticki** [comment]
LFTM. Do you think it would be fitting better in extra-utils?

**Comment by mmstick** [comment]
What is the criteria for what makes it into coreutils or extrautils?

**Comment by Ticki** [comment]
> What is the criteria for what makes it into coreutils or extrautils?

We don't have a hard limit, but those tools, which are less used, and not "core" in that sense, fits better for extrautils.

**Comment by mmstick** [comment]
I guess less used is different from person to person, as test and grep are some of my most-used commands.

**Comment by Ticki** [comment]
Well, yeah. Grep is extremely useful (I use it all the time), but it carries some complexity, due to regular expression and so on.

I rarely use `test`, but it might just be me. Anyone else?

**Comment by jackpot51** [comment]
`[` is typically an alias for test. Most shells use test for equivalence testing and other things, like `if [ -e file ]; then echo file exists; fi`

**Comment by jackpot51** [comment]
I think it belongs in coreutils

**Pull request merged**
