### PR TITLE
Date and Time man pages

### PR DESCRIPTION
**Pull request by rushsteve1**
I saw that the man pages for the `date` and `time` commands weren't done, so I decided to do them. Any issues please mention.

### CODE REVIEW

**Comment by ticki** [comment]
It doesn't compile. You need to enable the `-h` flag on the respective programs.

**Comment by rushsteve1** [comment]
Sorry about that, I forgot to comment out the `#![deny(warnings)]` which was causing it to abort the build when it warned about the unused `const`

I would be willing to add the argument handling and `-h` flags to the utils that are missing them, but that will take me until tonight because I'm away from my desk (That's why there are too many little commits, feel free to squash them if you want)

**Comment by jackpot51** [comment]
nice!

**Comment by jackpot51** [comment]
If you do -h, I can pull it, this is good

**Comment by rushsteve1** [comment]
I'm working on the help flags right now, nearly done.

**Comment by rushsteve1** [comment]
Committed and passing #64

**Pull request merged**
