### PR TITLE
Update to use new redox_users API

### PR DESCRIPTION
**Pull request by dlrobertson**
Updates to `stat` post `rust_users` API updates.

CC: @MggMuggins

### CODE REVIEW

**Comment by dlrobertson** [comment]
I think this needs to be updated. I think I was on a slightly out of date version of `redox_users`

**Comment by dlrobertson** [comment]
Just verified this works on master

**Comment by jackpot51** [comment]
Can you update the Cargo.lock?

**Comment by dlrobertson** [comment]
Updated

**Comment by MggMuggins** [comment]
For what you did around line ~65, I've mostly been using `unwrap_or_exit` for dealing with errors. It grabs the appropriate error message from the error it's called on, formats it with the name of the binary it was called with, and then spits out that string and exits. Very helpful, exits gracefully, and keeps source size down.

**Pull request merged**
