### PR TITLE
Completed Implementation of Cat

### PR DESCRIPTION
**Pull request by mmstick**
- Added exit_status to the Program structure to keep track of errors.
- Removed the vector for buffering the file and instead opted for printing to stdout directly.
- Implemented caret (^) and M- notation for showing non-printable characters.

### CODE REVIEW

**Comment by Ticki** [comment]
It still fails.

**Comment by mmstick** [comment]
That's because it's not this code that is causing the error. Recent commits added to master are causing all builds to fail, namely that a MAN_PAGE constant was added to many commands but those commands aren't using the constant in the code.

**Comment by Ticki** [comment]
Oh, right. The master is broken.

**Comment by Ticki** [comment]
:shipit:

**Pull request merged**
