### PR TITLE
adept pet project tr to redox coreutils

### PR DESCRIPTION
**Pull request by DaanHoogland**
not a functional tr yet, only some option processing done

### CODE REVIEW

**Comment by jackpot51** [comment]
@DaanHoogland when do you want me to merge this?

**Comment by DaanHoogland** [comment]
@jackpot51, I don't mean to wait till all functionality is available but at least some transaltion should be possible. I'll first implement the regular 1o1, "abc' to 'xyz' translation and then we can merge. ok?

**Comment by jackpot51** [comment]
sounds good @DaanHoogland !

**Comment by DaanHoogland** [comment]
@jackpot51 my first command line test done ;)
```
$ echo 'edaabcfg 
ijkabccccwow 
'n | /home/dahn/.cargo/bin/tr abc xyz
```
yields
```
edxxyzfg
ijkxyzzzzwow
n
```
I think this is now a buggy program that needs maintenance i.e. let's merge and go from there?

**Comment by jackpot51** [comment]
@DaanHoogland looks good, thanks!

**Pull request merged**
