### PR TITLE
Refactored cat.rs to use the coreutils::ArgParser.

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by simondesloges** [comment]
I've been looking at this pull request and thought I'd fix it, but you did it first!
Looking at the code, I think I found a possible bug: the -b option is supposed to override -n, as per the manpage, but the code does the opposite: -n will override -b, because the code that checks for -n is after the one that checks for -b.

**Comment by DaanHoogland** [comment]
@simondesloges that would be a good catch. I haven't looked at the intrinsics of the catting yet, just the option parsing and the global design. Could you send a PR to my branch so we can stream it in in one go, or is it separate enough to not conflict with each other?

**Comment by DaanHoogland** [comment]
@jackpot51 @stratact can you merge this? I don't think any work needs to be done on it.

**Comment by jackpot51** [comment]
awesome!

**Comment by DaanHoogland** [comment]
tnx, this means #36 can be closed as well

**Pull request merged**
