### PR TITLE
Adding seq to coreutils and updated README to reflect the changes.

### PR DESCRIPTION
**Pull request by GrappigPanda**
I'm pretty new to Rust, but I thought this would be a fun way to contribute to an interesting project.

If I'm doing anything that isn't idiomatic or that's just plain ugly, feel free to let me know and I'll change it!

### CODE REVIEW

**Comment by GrappigPanda** [comment]
Also, I'm curious about the goals of the coreutils project: is it planned to rewrite all of the common GNU coreutils to Rust for Redox?

**Comment by jackpot51** [comment]
Looks good to me, thanks! Yes, the goal is to write coreutils in Rust, targeting Redox as the default. Most of the bins also run on other platforms: Windows, OSX, and Linux.

**Comment by polymetric1** [comment]
Not the GNU coreutils! That's already been done (quite badly tbh) by uutils. We're trying to make extremely super minimal implementations of them

**Comment by polymetric1** [comment]
We're mostly basing these off of the BSD coreutils

**Comment by polymetric1** [comment]
By the way, maybe instead of ignoring any arguments after `2`, wrap the whole thing in a for loop skipping the first argument.

**Comment by jackpot51** [comment]
It should be, from the man page
```
Usage: seq LAST
  or:  seq FIRST LAST
  or:  seq FIRST INCREMENT LAST
```

**Comment by GrappigPanda** [comment]
Ahh, Iĺl take a look at this tomorrow and try and get everything updated. Got distracted working on an implementation of tail.

**Comment by jackpot51** [comment]
Tail would be awesome!

**Comment by GrappigPanda** [comment]
I have a new solution to seq including proper usage, as such:

```
Usage: seq LAST
  or:  seq FIRST LAST
  or:  seq FIRST INCREMENT LAST
```

But for using an increment, it seems the best way is to use a new feature to the language, so I'll probably wait until that's a proper feature of the language.

Regardless, I have most of tail done and should submit a PR tomorrow or later otnight.

**Comment by polymetric1** [comment]
I wonder if you could do that with clap..

**Comment by GrappigPanda** [comment]
Given that the argument parsing is getting much more cumbersome, an actual command-line parser could be tremendously helpful.

**Comment by polymetric1** [comment]
We're hoping to install clap in nearly every utility eventually.

**Comment by GrappigPanda** [comment]
Hmm, if that's the case, I have a working version of tail right now, but it essentially works just like:

```
tail <filename> <lines to read:optional>
```

I was just waiting until I found a better solution to argument parsing before I sent in a PR, should I wait until clap integration has already started to send in a PR or get the ball rolling and start using clap on tail?

**Comment by polymetric1** [comment]
Tip: conventionally <triangle brackets> are used for required arguments and [square brackets] are used for optional arguments

**Pull request merged**
