### PR TITLE
Add help to dd

### LINKED ISSUE #130: Add help to dd command
`dd`command can't show any help, we should add `-h` and `--help` options

### PR DESCRIPTION
**Pull request by Mojo4242**
closes #130

### CODE REVIEW

**Comment by tmccrmck** [comment]
You are missing the count opt. Perhaps we should consolidate this work into the other dd PR?

**Comment by Mojo4242** [comment]
Thanks for pointing this. Fixed :)
I will fix it conflicts with other dd pr

**Comment by tmccrmck** [comment]
Looks good :+1:

**Comment by Mojo4242** [comment]
closing, dd has a man now :)

**Pull request closed without merging**
